CREATE TABLE IF NOT EXISTS blog_view_count (
    slug        VARCHAR(200) NOT NULL PRIMARY KEY,
    view_count  BIGINT       NOT NULL DEFAULT 0,
    updated_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
