-- ENGINEER_PRACTICAL 2025년 제1회 기출 복원 — 20문항 일괄 적재
-- mock_exam: kind=PAST_EXAM, visibility=PUBLISHED, expert_verified=0

SET @seq := (SELECT COALESCE(MAX(sequence), 0) + 1 FROM mock_exam WHERE exam_type = 'ENGINEER_PRACTICAL');

INSERT INTO mock_exam
  (name, exam_type, sequence, visibility, expert_verified,
   kind, exam_year, exam_round, exam_date, created_at, updated_at)
VALUES
  ('정보처리기사 실기 2025년 1회 복원', 'ENGINEER_PRACTICAL', @seq, 'PUBLISHED', 0,
   'PAST_EXAM', 2025, 1, '2025-04-19', NOW(6), NOW(6));

SET @mock_exam_id := LAST_INSERT_ID();

INSERT INTO question
  (subject_id, content, question_type, correct_option, explanation,
   topic, difficulty, mock_exam_id, display_order,
   verification_category, content_hash, created_at, updated_at)
VALUES
  ((SELECT id FROM subject WHERE name = '보안' ORDER BY id LIMIT 1), '다음 설명에 해당하는 네트워크 공격 기법으로 가장 적절한 것은?\n\n**<설명>**\n정상 사용자의 세션 상태를 탈취하거나 도용하여 인증 없이 통신을 가로채는 공격 기법이다. TCP 연결이 수립된 이후 공격자가 시퀀스 번호 등을 조작해 정상 세션을 장악하는 방식이 대표적이다.\n\n① 세션 하이재킹\n② 스니핑\n③ 스푸핑\n④ 랜드 어택', 'MCQ', 1, '정답: 1. 세션 하이재킹은 정상 사용자의 세션을 가로채 권한을 탈취하는 공격 기법이다.\n\n**오답 풀이**\n- 1번: 세션을 탈취하거나 도용하는 공격이므로 정답이다.\n- 2번: 스니핑은 네트워크 패킷을 몰래 엿보는 행위이다.\n- 3번: 스푸핑은 IP, MAC, DNS 등을 위조하는 공격이다.\n- 4번: 랜드 어택은 출발지와 목적지 IP를 같게 조작하는 DoS 공격이다.\n\n**보충 개념**\n세션 하이재킹은 인증 이후의 세션을 탈취한다는 점이 핵심이다. TCP 세션 하이재킹은 시퀀스 번호 예측이나 조작을 이용할 수 있다.',
   '세션 하이재킹', 2, @mock_exam_id, 1, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '데이터베이스 이론' ORDER BY id LIMIT 1), '다음 제약조건 설명과 용어의 연결로 가장 적절한 것은?\n\n**<설명>**\nㄱ. 특정 속성에 입력될 수 있는 값의 범위나 형식을 제한한다.\nㄴ. 기본키는 NULL이 될 수 없고 중복될 수 없다는 무결성이다.\nㄷ. 외래키 값은 참조하는 부모 테이블의 값과 일관성을 유지해야 한다.\n\n**<보기>**\n개체, 참조, 도메인\n\n① ㄱ-도메인, ㄴ-개체, ㄷ-참조\n② ㄱ-개체, ㄴ-도메인, ㄷ-참조\n③ ㄱ-참조, ㄴ-개체, ㄷ-도메인\n④ ㄱ-도메인, ㄴ-참조, ㄷ-개체', 'MCQ', 1, '정답: 1. 값의 범위 제한은 도메인 무결성, 기본키 관련 제약은 개체 무결성, 외래키 관련 제약은 참조 무결성이다.\n\n**오답 풀이**\n- 1번: 세 무결성의 의미가 모두 올바르게 연결되었다.\n- 2번: ㄱ과 ㄴ의 연결이 바뀌었다.\n- 3번: ㄱ과 ㄷ의 연결이 바뀌었다.\n- 4번: ㄴ과 ㄷ의 연결이 바뀌었다.\n\n**보충 개념**\n개체 무결성은 기본키, 참조 무결성은 외래키, 도메인 무결성은 속성 값의 범위와 형식 제약과 관련된다.',
   '무결성', 1, @mock_exam_id, 2, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '네트워크/OS' ORDER BY id LIMIT 1), '다음 설명에 해당하는 오류 검출 기법의 영문 약자로 가장 적절한 것은?\n\n**<설명>**\n데이터 전송이나 저장 과정에서 오류를 감지하기 위해 사용하는 오류 검출 코드이다. 데이터에 검사 값을 추가하고, 수신 또는 읽기 시 다시 계산하여 데이터 변경 여부를 확인한다. 정해진 다항식을 기반으로 2진수 나눗셈을 수행하고 나머지를 검사 값으로 사용한다.\n\n① CRC\n② MAC\n③ ARP\n④ RARP', 'MCQ', 1, '정답: 1. CRC는 순환 중복 검사로, 다항식 나눗셈의 나머지를 이용해 오류를 검출한다.\n\n**오답 풀이**\n- 1번: 데이터 오류 검출 기법이므로 정답이다.\n- 2번: MAC은 매체 접근 제어 또는 메시지 인증 코드 등 다른 의미로 쓰인다.\n- 3번: ARP는 IP 주소를 MAC 주소로 변환하는 프로토콜이다.\n- 4번: RARP는 MAC 주소를 IP 주소로 변환하는 프로토콜이다.\n\n**보충 개념**\nCRC는 네트워크 프레임, 저장 장치 등에서 데이터 무결성 검사용으로 사용된다. 오류 정정이 아니라 오류 검출에 초점이 있다.',
   'CRC', 2, @mock_exam_id, 3, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '보안' ORDER BY id LIMIT 1), '다음 설명에 해당하는 악성 소프트웨어 유형으로 가장 적절한 것은?\n\n**<설명>**\n사용자에게 가짜 바이러스 경고나 시스템 문제를 보여 주어 공포심을 유발하고, 불필요한 결제나 소프트웨어 설치를 유도한다. ''겁을 주다''라는 의미에서 유래한 용어이다.\n\n① 애드웨어\n② 스캐어웨어\n③ 그룹웨어\n④ 컴포넌트웨어', 'MCQ', 2, '정답: 2. 스캐어웨어는 사용자의 불안과 공포를 이용해 결제나 설치를 유도하는 악성 소프트웨어 유형이다.\n\n**오답 풀이**\n- 1번: 애드웨어는 광고를 노출하는 소프트웨어이다.\n- 2번: 공포심을 이용하는 악성 소프트웨어이므로 정답이다.\n- 3번: 그룹웨어는 협업 지원 소프트웨어이다.\n- 4번: 컴포넌트웨어는 소프트웨어 부품화 개념과 관련된다.\n\n**보충 개념**\n스캐어웨어는 사회공학적 기법을 이용한다. 실제 감염 여부와 무관하게 경고를 띄우고 결제를 유도하는 경우가 많다.',
   '스캐어웨어', 1, @mock_exam_id, 4, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'Java' ORDER BY id LIMIT 1), '다음 Java 코드의 출력 결과로 가장 적절한 것은?\n\n```java\npublic class Main {\n  public static void main(String[] args) {\n    int a = 5, b = 0;\n    try {\n      System.out.print(a / b);\n    } catch (ArithmeticException e) {\n      System.out.print("출력1");\n    } catch (ArrayIndexOutOfBoundsException e) {\n      System.out.print("출력2");\n    } catch (NumberFormatException e) {\n      System.out.print("출력3");\n    } catch (Exception e) {\n      System.out.print("출력4");\n    } finally {\n      System.out.print("출력5");\n    }\n  }\n}\n```\n\n① 출력1출력5\n② 출력2출력5\n③ 출력4출력5\n④ 출력5', 'MCQ', 1, '정답: 1. 5를 0으로 나누면 ArithmeticException이 발생하여 첫 번째 catch가 실행되고, finally 블록도 실행된다.\n\n**오답 풀이**\n- 1번: ArithmeticException 처리 후 finally가 실행되므로 정답이다.\n- 2번: 배열 인덱스 예외가 발생하지 않는다.\n- 3번: ArithmeticException이 먼저 매칭되므로 Exception catch까지 가지 않는다.\n- 4번: catch 블록 출력이 누락되었다.\n\n**보충 개념**\nJava에서 finally 블록은 예외 발생 여부와 관계없이 일반적으로 실행된다. 여러 catch가 있을 때는 위에서부터 타입이 맞는 catch가 실행된다.',
   'Java 예외 처리', 2, @mock_exam_id, 5, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '네트워크/OS' ORDER BY id LIMIT 1), 'ARP와 RARP에 대한 설명으로 가장 적절한 것은?\n\n① ARP는 IP 주소를 MAC 주소로 변환하고, RARP는 MAC 주소를 IP 주소로 변환한다.\n② ARP는 MAC 주소를 IP 주소로 변환하고, RARP는 IP 주소를 MAC 주소로 변환한다.\n③ ARP와 RARP는 모두 도메인 이름을 IP 주소로 변환한다.\n④ ARP와 RARP는 모두 오류 검출 코드를 생성한다.', 'MCQ', 1, '정답: 1. ARP는 IP 주소에 대응하는 MAC 주소를 찾고, RARP는 MAC 주소에 대응하는 IP 주소를 찾는다.\n\n**오답 풀이**\n- 1번: 두 프로토콜의 역할이 올바르게 연결되었다.\n- 2번: ARP와 RARP의 설명이 반대이다.\n- 3번: 도메인 이름을 IP 주소로 변환하는 것은 DNS이다.\n- 4번: 오류 검출 코드는 CRC와 관련된다.\n\n**보충 개념**\nARP는 같은 네트워크 내 통신에서 IP 주소를 기반으로 MAC 주소를 알아내는 데 사용된다. RARP는 과거 디스크 없는 장비가 자신의 IP를 알아낼 때 사용되었다.',
   'ARP', 1, @mock_exam_id, 6, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'SQL' ORDER BY id LIMIT 1), '다음 SQL 실행 결과로 가장 적절한 것은?\n\n**<조건>**\nemp 테이블과 sal 테이블을 id 기준으로 조인하고, incentive가 500 이상인 행만 조회한다. 조건을 만족하는 행은 이순신 1건이며 incentive 값은 1000이다.\n\n```sql\nSELECT name, incentive\nFROM emp, sal\nWHERE emp.id = sal.id\n  AND incentive >= 500;\n```\n\n① 이순신 | 1000\n② 이순신 | 500\n③ 강감찬 | 1000\n④ 결과 없음', 'MCQ', 1, '정답: 1. id가 일치하고 incentive가 500 이상인 행이 이순신 1건이며 값은 1000이다.\n\n**오답 풀이**\n- 1번: 조인 조건과 필터 조건을 모두 만족하는 결과이다.\n- 2번: incentive 값을 잘못 제시했다.\n- 3번: 조건을 만족하는 이름이 다르다.\n- 4번: 조건을 만족하는 행이 존재한다.\n\n**보충 개념**\n구식 조인 문법에서는 FROM 절에 테이블을 나열하고 WHERE 절에 조인 조건과 필터 조건을 함께 작성한다. 컬럼명이 여러 테이블에 동시에 존재할 수 있으면 테이블 별칭을 붙여 명확히 작성하는 것이 좋다.',
   'SQL JOIN', 2, @mock_exam_id, 7, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '데이터베이스 이론' ORDER BY id LIMIT 1), '다음 데이터베이스 용어와 설명의 연결로 가장 적절한 것은?\n\n**<설명>**\n1. 릴레이션에서 속성의 개수\n2. 릴레이션에서 튜플의 개수\n3. 다른 릴레이션의 기본키를 참조하는 속성\n4. 특정 속성에 입력될 수 있는 값의 유형이나 범위\n\n**<보기>**\nㄱ. domain  ㄴ. primary  ㄷ. degree  ㄹ. candidate  ㅁ. cardinality  ㅂ. attribute  ㅅ. foreign\n\n① 1-ㄷ, 2-ㅁ, 3-ㅅ, 4-ㄱ\n② 1-ㅁ, 2-ㄷ, 3-ㅅ, 4-ㄱ\n③ 1-ㄷ, 2-ㅁ, 3-ㄴ, 4-ㅂ\n④ 1-ㅂ, 2-ㄹ, 3-ㅅ, 4-ㄱ', 'MCQ', 1, '정답: 1. 속성 수는 degree, 튜플 수는 cardinality, 참조 속성은 foreign key, 값의 범위는 domain이다.\n\n**오답 풀이**\n- 1번: 모든 연결이 적절하다.\n- 2번: degree와 cardinality가 바뀌었다.\n- 3번: 외래키를 primary로 잘못 연결했다.\n- 4번: degree와 cardinality의 의미가 맞지 않는다.\n\n**보충 개념**\n릴레이션의 차수(degree)는 속성 수, 카디널리티(cardinality)는 튜플 수이다. 도메인은 속성이 가질 수 있는 값의 범위이다.',
   '관계형 데이터 모델', 2, @mock_exam_id, 8, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '네트워크/OS' ORDER BY id LIMIT 1), 'IP 주소가 `192.168.35.10`, 서브넷 마스크가 `255.255.252.0`인 PC와 같은 네트워크에 속하는 IP로 가장 적절한 것은?\n\n**<보기>**\nㄱ. 192.168.34.1\nㄴ. 192.168.32.19\nㄷ. 192.168.35.200\nㄹ. 192.168.33.138\nㅁ. 192.168.35.50\n\n① ㄱ, ㄴ, ㄷ, ㄹ, ㅁ\n② ㄱ, ㄷ, ㅁ\n③ ㄴ, ㄹ\n④ ㄷ, ㅁ', 'MCQ', 1, '정답: 1. 255.255.252.0은 /22이며, 192.168.35.10은 192.168.32.0~192.168.35.255 범위에 속한다. 제시된 IP는 모두 이 범위에 포함된다.\n\n**오답 풀이**\n- 1번: 모든 IP가 같은 /22 네트워크 범위에 포함된다.\n- 2번: ㄴ과 ㄹ도 같은 네트워크에 속한다.\n- 3번: ㄱ, ㄷ, ㅁ도 같은 네트워크에 속한다.\n- 4번: 일부만 포함한 선택지이다.\n\n**보충 개념**\n/22는 세 번째 옥텟 단위로 4씩 증가하는 네트워크 블록을 만든다. 35가 포함되는 블록은 32~35이다.',
   '서브넷', 3, @mock_exam_id, 9, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'C언어' ORDER BY id LIMIT 1), '다음 C 코드의 출력 결과로 가장 적절한 것은?\n\n```c\n#include <stdio.h>\n\nchar Data[5] = {''B'', ''A'', ''D'', ''E''};\nchar c;\n\nint main() {\n    int i, temp, temp2;\n    c = ''C'';\n    printf("%d\\n", Data[3] - Data[1]);\n\n    for (i = 0; i < 5; ++i) {\n        if (Data[i] > c)\n            break;\n    }\n\n    temp = Data[i];\n    Data[i] = c;\n    i++;\n\n    for (; i < 5; ++i) {\n        temp2 = Data[i];\n        Data[i] = temp;\n        temp = temp2;\n    }\n\n    for (i = 0; i < 5; i++) {\n        printf("%c", Data[i]);\n    }\n}\n```\n\n① 4\nBACDE\n② 4\nBADEC\n③ 3\nBACDE\n④ 4\nABCDE', 'MCQ', 1, '정답: 1. ''E'' - ''A''는 ASCII 코드 차이로 4이고, ''C''를 첫 번째로 자신보다 큰 문자 D 위치에 삽입하면 배열은 B, A, C, D, E가 된다.\n\n**오답 풀이**\n- 1번: 첫 줄 4와 최종 문자열 BACDE가 맞다.\n- 2번: 삽입 후 뒤 원소 이동이 잘못 계산되었다.\n- 3번: ASCII 코드 차이를 잘못 계산했다.\n- 4번: 기존 배열 순서를 완전 정렬한 것이 아니다.\n\n**보충 개념**\n문자끼리 뺄셈하면 해당 문자의 정수 코드값 차이가 계산된다. C의 전역 char 배열은 명시하지 않은 마지막 원소가 ''\\0''으로 초기화된다.',
   'C 배열', 4, @mock_exam_id, 10, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'C언어' ORDER BY id LIMIT 1), '다음 C 코드의 출력 결과로 가장 적절한 것은?\n\n```c\n#include <stdio.h>\n#include <stdlib.h>\n\nvoid set(int** arr, int* data, int rows, int cols) {\n    for (int i = 0; i < rows * cols; ++i) {\n        arr[((i + 1) / rows) % rows][(i + 1) % cols] = data[i];\n    }\n}\n\nint main() {\n    int rows = 3, cols = 3, sum = 0;\n    int data[] = {5, 2, 7, 4, 1, 8, 3, 6, 9};\n    int** arr = (int**)malloc(sizeof(int*) * rows);\n\n    for (int i = 0; i < cols; i++) {\n        arr[i] = (int*)malloc(sizeof(int) * cols);\n    }\n\n    set(arr, data, rows, cols);\n\n    for (int i = 0; i < rows * cols; i++) {\n        sum += arr[i / rows][i % cols] * (i % 2 == 0 ? 1 : -1);\n    }\n\n    for (int i = 0; i < rows; i++) {\n        free(arr[i]);\n    }\n    free(arr);\n\n    printf("%d", sum);\n}\n```\n\n① 13\n② 12\n③ 9\n④ 15', 'MCQ', 1, '정답: 1. set 함수 수행 후 배열은 [9,5,2], [7,4,1], [8,3,6] 형태가 된다. 이후 짝수 인덱스는 더하고 홀수 인덱스는 빼면 9-5+2-7+4-1+8-3+6 = 13이다.\n\n**오답 풀이**\n- 1번: 배열 배치와 부호 계산을 올바르게 추적한 결과이다.\n- 2번: 일부 원소의 부호를 잘못 적용한 값이다.\n- 3번: 배열 배치 순서를 단순 행 우선으로 착각한 값이다.\n- 4번: 특정 원소를 누락하거나 중복 계산한 값이다.\n\n**보충 개념**\n포인터 배열로 만든 2차원 배열은 인덱스 계산을 정확히 추적해야 한다. `%`와 `/` 연산이 행과 열 계산에 어떻게 사용되는지 확인해야 한다.',
   'C 포인터 배열', 5, @mock_exam_id, 11, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '소프트웨어 설계' ORDER BY id LIMIT 1), '다음 결합도 설명과 용어의 연결로 가장 적절한 것은?\n\n**<설명>**\n1. 다른 모듈 내부의 변수나 기능을 직접 사용하는 경우\n2. 모듈 간 인터페이스로 배열, 객체, 자료구조 등이 전달되는 경우\n3. 파라미터가 아닌 모듈 밖 전역 변수를 참조하거나 갱신하는 경우\n\n**<보기>**\nㄱ. 자료 결합도  ㄴ. 스탬프 결합도  ㄷ. 제어 결합도  ㄹ. 공통 결합도  ㅁ. 내용 결합도  ㅂ. 외부 결합도\n\n① 1-ㅁ, 2-ㄴ, 3-ㄹ\n② 1-ㄱ, 2-ㄴ, 3-ㄷ\n③ 1-ㄹ, 2-ㅁ, 3-ㄴ\n④ 1-ㅂ, 2-ㄱ, 3-ㄹ', 'MCQ', 1, '정답: 1. 모듈 내부를 직접 참조하면 내용 결합도, 자료구조 전달은 스탬프 결합도, 전역 변수 공유는 공통 결합도이다.\n\n**오답 풀이**\n- 1번: 세 설명과 결합도 유형이 모두 올바르게 연결되었다.\n- 2번: 내부 직접 참조를 자료 결합도로 잘못 연결했다.\n- 3번: 세 연결이 모두 부적절하다.\n- 4번: 자료구조 전달은 자료 결합도가 아니라 스탬프 결합도이다.\n\n**보충 개념**\n결합도는 모듈 간 의존 정도를 의미한다. 일반적으로 내용 결합도가 가장 강하고, 자료 결합도가 가장 약한 결합도에 속한다.',
   '결합도', 2, @mock_exam_id, 12, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'Java' ORDER BY id LIMIT 1), '다음 Java 코드의 출력 결과로 가장 적절한 것은?\n\n```java\npublic class Main {\n    public static void main(String[] args) {\n        new Child();\n        System.out.println(Parent.total);\n    }\n}\n\nclass Parent {\n    static int total = 0;\n    int v = 1;\n\n    public Parent() {\n        total += (++v);\n        show();\n    }\n\n    public void show() {\n        total += total;\n    }\n}\n\nclass Child extends Parent {\n    int v = 10;\n\n    public Child() {\n        v += 2;\n        total += v++;\n        show();\n    }\n\n    @Override\n    public void show() {\n        total += total * 2;\n    }\n}\n```\n\n① 54\n② 18\n③ 36\n④ 72', 'MCQ', 1, '정답: 1. Parent 생성자에서 Parent의 v가 1에서 2가 되어 total은 2가 된다. 생성자 안의 show()는 동적 바인딩으로 Child의 show()가 호출되어 total은 6이 된다. 이후 Child 필드 v가 10으로 초기화되고 Child 생성자에서 v += 2로 12가 된 뒤 total에 12를 더해 18이 된다. 마지막 show()로 total은 54가 된다.\n\n**오답 풀이**\n- 1번: 생성자 호출 순서와 오버라이딩 메서드 호출을 올바르게 반영했다.\n- 2번: 마지막 show 호출을 누락한 값이다.\n- 3번: show의 계산식을 잘못 적용한 값이다.\n- 4번: total 누적 과정을 과대 계산한 값이다.\n\n**보충 개념**\nJava 생성자 실행 중에도 오버라이딩된 메서드는 동적 바인딩으로 자식 클래스 메서드가 호출될 수 있다. 이 경우 필드 초기화 순서에 주의해야 한다.',
   'Java 상속', 5, @mock_exam_id, 13, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '소프트웨어 설계' ORDER BY id LIMIT 1), '다음 설명에 해당하는 디자인 패턴으로 가장 적절한 것은?\n\n**<설명>**\n서로 다른 인터페이스를 가진 클래스들을 함께 사용할 수 있도록 변환한다. 기존 클래스 객체를 감싸 원하는 인터페이스에 맞게 연결해 주는 역할을 한다.\n\n① Adapter\n② Singleton\n③ Observer\n④ Factory Method', 'MCQ', 1, '정답: 1. Adapter 패턴은 호환되지 않는 인터페이스를 가진 객체들을 함께 사용할 수 있도록 중간에서 변환해 준다.\n\n**오답 풀이**\n- 1번: 인터페이스 변환 역할을 하므로 정답이다.\n- 2번: Singleton은 인스턴스를 하나만 생성하도록 보장하는 패턴이다.\n- 3번: Observer는 상태 변화 알림을 구독자에게 전달하는 패턴이다.\n- 4번: Factory Method는 객체 생성 책임을 하위 클래스에 위임하는 패턴이다.\n\n**보충 개념**\nAdapter 패턴의 주요 구성 요소는 Target, Adapter, Adaptee, Client이다. 기존 코드를 수정하지 않고 인터페이스를 맞출 때 유용하다.',
   'Adapter 패턴', 1, @mock_exam_id, 14, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '소프트웨어 설계' ORDER BY id LIMIT 1), '다음 코드에 대해 문장 커버리지 테스트를 수행하려고 한다. 문장 번호와 실행 순서로 가장 적절한 것은?\n\n```c\nint main(int b[], int m, int x) {\n    int a = 0;                         // ①\n    while (a < m && b[a] < x) {        // ②\n        if (b[a] < 0)                  // ③\n            b[a] = -b[a];              // ④\n        a++;                           // ⑤\n    }\n    return 1;                          // ⑥\n}\n```\n\n**<조건>**\n문장 ④가 한 번 실행되고, 그 다음 while 조건이 거짓이 되어 반복문을 종료하는 테스트 경로를 기준으로 한다.\n\n① ①→②→③→④→⑤→②→⑥\n② ①→②→③→⑤→②→⑥\n③ ①→②→⑥\n④ ②→③→④→⑤→①→⑥', 'MCQ', 1, '정답: 1. 초기화 문장 ①을 수행한 뒤 while 조건 ②가 참이 되어 반복문에 진입한다. if 조건 ③이 참이면 문장 ④가 실행되고, 이후 증가 문장 ⑤가 실행된다. 다음 while 조건 ②가 거짓이 되면 반복문을 빠져나와 return 문장 ⑥을 실행한다.\n\n**오답 풀이**\n- 1번: 조건에서 제시한 테스트 경로의 실행 순서와 일치한다.\n- 2번: 문장 ④가 실행되는 경로가 아니다.\n- 3번: 반복문 내부 문장이 실행되지 않는 경로이다.\n- 4번: 초기화 문장 ①이 조건 검사보다 먼저 실행되어야 하므로 순서가 틀렸다.\n\n**보충 개념**\n문장 커버리지는 프로그램의 모든 문장이 최소 한 번 이상 실행되도록 테스트 경로를 선정하는 기준이다. 실행 순서를 묻는 문항은 입력 조건 또는 테스트 경로가 명확히 제시되어야 한다.',
   '문장 커버리지', 4, @mock_exam_id, 15, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'Java' ORDER BY id LIMIT 1), '다음 Java 코드의 출력 결과로 가장 적절한 것은?\n\n```java\npublic class Main {\n    public static void main(String[] args) {\n        int[] data = {3, 5, 8, 12, 17};\n        System.out.println(func(data, 0, data.length - 1));\n    }\n\n    static int func(int[] a, int st, int end) {\n        if (st >= end) return 0;\n        int mid = (st + end) / 2;\n        return a[mid] + Math.max(func(a, st, mid), func(a, mid + 1, end));\n    }\n}\n```\n\n① 20\n② 17\n③ 25\n④ 8', 'MCQ', 1, '정답: 1. 최초 호출 func(a,0,4)에서 mid는 2이므로 a[2]=8을 더한다. 왼쪽 func(a,0,2)는 8, 오른쪽 func(a,3,4)는 12를 반환하므로 8 + max(8, 12) = 20이다.\n\n**오답 풀이**\n- 1번: 재귀 호출과 Math.max 결과를 올바르게 계산한 값이다.\n- 2번: 배열의 마지막 값과 혼동한 값이다.\n- 3번: 여러 값을 단순 합산한 값이다.\n- 4번: 최초 mid 값만 반환한 경우이다.\n\n**보충 개념**\n재귀 함수는 종료 조건과 분할 범위를 정확히 추적해야 한다. 이 코드는 중간값을 더하고 양쪽 재귀 결과 중 큰 값을 선택한다.',
   'Java 재귀', 4, @mock_exam_id, 16, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'Python' ORDER BY id LIMIT 1), '다음 Python 코드의 출력 결과로 가장 적절한 것은?\n\n```python\nclass Node:\n    def __init__(self, value):\n        self.value = value\n        self.children = []\n\ndef tree(li):\n    nodes = [Node(i) for i in li]\n    for i in range(1, len(li)):\n        nodes[(i - 1) // 2].children.append(nodes[i])\n    return nodes[0]\n\ndef calc(node, level=0):\n    if node is None:\n        return 0\n    return (node.value if level % 2 == 1 else 0) + sum(calc(n, level + 1) for n in node.children)\n\nli = [3, 5, 8, 12, 15, 18, 21]\nroot = tree(li)\nprint(calc(root))\n```\n\n① 13\n② 3\n③ 33\n④ 26', 'MCQ', 1, '정답: 1. calc는 홀수 레벨의 노드 값만 더한다. 루트 3은 레벨 0이라 제외되고, 레벨 1의 값 5와 8이 더해져 13이 출력된다.\n\n**오답 풀이**\n- 1번: 홀수 레벨 값 5와 8의 합이다.\n- 2번: 루트 값만 계산한 값이다.\n- 3번: 일부 자식 노드까지 잘못 포함한 값이다.\n- 4번: 짝수 레벨 또는 전체 합 일부를 혼동한 값이다.\n\n**보충 개념**\n완전 이진트리 배열 표현에서 인덱스 i의 부모는 `(i-1)//2`이다. 재귀 함수의 level 값이 어떤 노드를 포함할지 결정한다.',
   'Python 트리', 4, @mock_exam_id, 17, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'C언어' ORDER BY id LIMIT 1), '다음 C 코드의 출력 결과로 가장 적절한 것은?\n\n```c\n#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct Data {\n    int value;\n    struct Data *next;\n} Data;\n\nData* insert(Data* head, int value) {\n    Data* new_node = (Data*)malloc(sizeof(Data));\n    new_node->value = value;\n    new_node->next = head;\n    return new_node;\n}\n\nData* reconnect(Data* head, int value) {\n    if (head == NULL || head->value == value) return head;\n    Data *prev = NULL, *curr = head;\n    while (curr != NULL && curr->value != value) {\n        prev = curr;\n        curr = curr->next;\n    }\n    if (curr != NULL && prev != NULL) {\n        prev->next = curr->next;\n        curr->next = head;\n        head = curr;\n    }\n    return head;\n}\n\nint main() {\n    Data *head = NULL, *curr;\n    for (int i = 1; i <= 5; i++)\n        head = insert(head, i);\n    head = reconnect(head, 3);\n    for (curr = head; curr != NULL; curr = curr->next)\n        printf("%d", curr->value);\n    return 0;\n}\n```\n\n① 35421\n② 12345\n③ 54321\n④ 34521', 'MCQ', 1, '정답: 1. insert는 새 노드를 head 앞에 붙이므로 최초 리스트는 5→4→3→2→1이다. reconnect(head, 3)은 값 3 노드를 맨 앞으로 옮기므로 3→5→4→2→1이 된다.\n\n**오답 풀이**\n- 1번: 연결 리스트 삽입 순서와 재연결 결과가 맞다.\n- 2번: 뒤에 삽입되는 방식으로 착각한 값이다.\n- 3번: reconnect 수행 전 리스트이다.\n- 4번: 4와 5의 순서를 잘못 계산한 값이다.\n\n**보충 개념**\n단일 연결 리스트에서 노드를 앞으로 이동하려면 이전 노드의 next를 현재 노드 다음으로 바꾸고, 현재 노드의 next를 기존 head로 연결해야 한다.',
   'C 연결 리스트', 4, @mock_exam_id, 18, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'C언어' ORDER BY id LIMIT 1), '다음 C 코드의 출력 결과로 가장 적절한 것은?\n\n```c\n#include <stdio.h>\n\ntypedef struct student {\n    char* name;\n    int score[3];\n} Student;\n\nint dec(int enc) {\n    return enc & 0xA5;\n}\n\nint sum(Student* p) {\n    return dec(p->score[0]) + dec(p->score[1]) + dec(p->score[2]);\n}\n\nint main() {\n    Student s[2] = {\n        "Kim", {0xA0, 0xA5, 0xDB},\n        "Lee", {0xA0, 0xED, 0x81}\n    };\n    int result = 0;\n    for (int i = 0; i < 2; i++) {\n        result += sum(&s[i]);\n    }\n    printf("%d", result);\n    return 0;\n}\n```\n\n① 908\n② 806\n③ 512\n④ 1024', 'MCQ', 1, '정답: 1. 각 점수에 대해 비트 AND 연산 `enc & 0xA5`를 수행하면 160, 165, 129, 160, 165, 129가 된다. 이를 모두 합산하면 908이다.\n\n**오답 풀이**\n- 1번: 비트 AND 결과를 모두 합산한 값이다.\n- 2번: 일부 16진수 값을 10진수로 잘못 변환한 값이다.\n- 3번: AND 연산 대신 일부 값만 더한 경우이다.\n- 4번: 16진수 자리수를 단순 합산한 값과 혼동한 것이다.\n\n**보충 개념**\nC에서 `&`는 비트 단위 AND 연산자이다. 16진수 값을 2진수로 변환해 같은 자리의 비트가 모두 1인 경우만 1로 남는다.',
   'C 비트 연산', 4, @mock_exam_id, 19, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'Java' ORDER BY id LIMIT 1), '다음 Java 코드의 출력 결과로 가장 적절한 것은?\n\n```java\npublic class Main {\n  public static void main(String[] args) {\n    System.out.println(calc("5"));\n  }\n\n  static int calc(int value) {\n    if (value <= 1) return value;\n    return calc(value - 1) + calc(value - 2);\n  }\n\n  static int calc(String str) {\n    int value = Integer.valueOf(str);\n    if (value <= 1) return value;\n    return calc(value - 1) + calc(value - 3);\n  }\n}\n```\n\n① 4\n② 5\n③ 7\n④ 8', 'MCQ', 1, '정답: 1. main에서는 문자열 인자를 전달하므로 calc(String)이 먼저 호출된다. calc("5")는 calc(4) + calc(2)를 계산하고, int 버전의 재귀 결과는 각각 3과 1이므로 합은 4이다.\n\n**오답 풀이**\n- 1번: 오버로딩 선택과 재귀 계산을 올바르게 반영했다.\n- 2번: 일반 피보나치 F(5)와 혼동한 값이다.\n- 3번: calc(5) int 버전 결과와 혼동한 값이다.\n- 4번: 재귀 호출 범위를 과대 계산한 값이다.\n\n**보충 개념**\nJava 오버로딩은 컴파일 시점의 인자 타입에 따라 호출 메서드가 결정된다. 문자열 "5"는 calc(String)을 호출하고, 그 내부의 정수 연산 결과는 calc(int)를 호출한다.',
   'Java 오버로딩', 4, @mock_exam_id, 20, 'NONE', NULL, NOW(6), NOW(6))
;