-- ENGINEER_PRACTICAL 2025년 제3회 기출 복원 — 20문항 일괄 적재
-- mock_exam: kind=PAST_EXAM, visibility=PUBLISHED, expert_verified=0

SET @seq := (SELECT COALESCE(MAX(sequence), 0) + 1 FROM mock_exam WHERE exam_type = 'ENGINEER_PRACTICAL');

INSERT INTO mock_exam
  (name, exam_type, sequence, visibility, expert_verified,
   kind, exam_year, exam_round, exam_date, created_at, updated_at)
VALUES
  ('정보처리기사 실기 2025년 3회 복원', 'ENGINEER_PRACTICAL', @seq, 'PUBLISHED', 0,
   'PAST_EXAM', 2025, 3, '2025-11-01', NOW(6), NOW(6));

SET @mock_exam_id := LAST_INSERT_ID();

INSERT INTO question
  (subject_id, content, question_type, correct_option, explanation,
   topic, difficulty, mock_exam_id, display_order,
   verification_category, content_hash, created_at, updated_at)
VALUES
  ((SELECT id FROM subject WHERE name = '소프트웨어 설계' ORDER BY id LIMIT 1), '다음은 UML 구조 다이어그램에 대한 설명이다. 괄호 안에 공통으로 들어갈 용어로 가장 적절한 것은?\n\n**<설명>**\n시스템을 폴더 모양의 단위로 구분하여 구성 요소 간 관계를 표현하는 UML 구조 다이어그램이다. 하나의 단위 안에는 여러 클래스나 하위 단위가 포함될 수 있으며, 단위 간에는 «import», «access», «merge» 등의 관계를 통해 의존성을 표현한다. 코드의 실제 폴더 구조와 비슷하게 표현되므로 소프트웨어의 모듈화, 재사용성, 의존 관계를 시각적으로 설계할 때 사용된다.\n\n① 패키지\n② 클래스\n③ 시퀀스\n④ 상태', 'MCQ', 1, '정답: 1. 폴더 모양 단위로 시스템 구성 요소와 의존 관계를 표현하는 UML 구조 다이어그램은 패키지 다이어그램이다.\n\n**오답 풀이**\n- 1번: 패키지 단위와 패키지 간 의존 관계를 표현하므로 정답이다.\n- 2번: 클래스 다이어그램은 클래스, 속성, 메서드, 관계를 표현한다.\n- 3번: 시퀀스 다이어그램은 객체 간 메시지 흐름을 시간 순서로 표현한다.\n- 4번: 상태 다이어그램은 객체 상태 변화와 전이를 표현한다.\n\n**보충 개념**\n패키지 다이어그램은 UML 구조 다이어그램 중 하나이다. 패키지 간 의존 관계에는 import, access, merge 등이 사용될 수 있다.',
   '패키지 다이어그램', 2, @mock_exam_id, 1, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '소프트웨어 설계' ORDER BY id LIMIT 1), '다음 설명에 해당하는 화이트박스 테스트 커버리지 기준은?\n\n**<설명>**\n결정 포인트 안에 존재하는 모든 개별 조건식이 True와 False를 각각 한 번 이상 만족하도록 테스트 케이스를 설계한다. 다만 전체 결정식의 결과 True/False가 모두 수행된다고 보장하지는 않는다.\n\n**<보기>**\nㄱ. 경로(Path)\nㄴ. 결정(Decision)\nㄷ. 조건/결정(Condition/Decision)\nㄹ. 변경 조건/결정(MC/DC)\nㅁ. 다중 조건(Multiple Condition)\nㅂ. 문장(Statement)\nㅅ. 분기(Branch)\nㅇ. 조건(Condition)\n\n① ㄴ\n② ㄷ\n③ ㅇ\n④ ㅁ', 'MCQ', 3, '정답: 3. 개별 조건식 각각이 True와 False를 한 번 이상 갖도록 하는 기준은 조건 커버리지이다.\n\n**오답 풀이**\n- 1번: 결정 커버리지는 전체 결정식의 True/False 결과를 확인한다.\n- 2번: 조건/결정 커버리지는 개별 조건과 전체 결정 결과를 모두 고려한다.\n- 3번: 개별 조건식의 True/False를 대상으로 하므로 정답이다.\n- 4번: 다중 조건 커버리지는 개별 조건 조합 전체를 고려한다.\n\n**보충 개념**\n조건 커버리지는 각 원자 조건의 참과 거짓을 확인한다. 하지만 결정문 전체 결과의 참과 거짓을 반드시 보장하지는 않는다.',
   '조건 커버리지', 2, @mock_exam_id, 2, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '네트워크/OS' ORDER BY id LIMIT 1), '다음 유닉스/리눅스 기본 명령어 설명에 맞게 연결한 것으로 가장 적절한 것은?\n\n**<설명>**\n1. 현재 작업 중인 디렉터리의 경로를 출력한다.\n2. 디렉터리의 내용, 파일 및 하위 디렉터리를 목록으로 표시한다.\n3. 다른 디렉터리로 이동한다.\n4. 파일을 복사한다.\n\n**<보기>**\nls, cd, cp, pwd\n\n① 1-pwd, 2-ls, 3-cd, 4-cp\n② 1-ls, 2-pwd, 3-cd, 4-cp\n③ 1-cd, 2-ls, 3-pwd, 4-cp\n④ 1-pwd, 2-cp, 3-cd, 4-ls', 'MCQ', 1, '정답: 1. pwd는 현재 경로 출력, ls는 목록 출력, cd는 디렉터리 이동, cp는 파일 복사 명령이다.\n\n**오답 풀이**\n- 1번: 네 명령어가 모두 올바르게 연결되었다.\n- 2번: pwd와 ls가 바뀌었다.\n- 3번: cd와 pwd의 역할이 바뀌었다.\n- 4번: ls와 cp의 역할이 바뀌었다.\n\n**보충 개념**\n리눅스 기본 명령어는 실기에서 단답형으로 자주 출제된다. pwd, ls, cd, cp, mv, rm 등의 기능을 구분해야 한다.',
   '리눅스 명령어', 1, @mock_exam_id, 3, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '네트워크/OS' ORDER BY id LIMIT 1), '다음 오류 검출 및 정정 방식 설명의 빈칸 ①~⑤에 들어갈 용어를 순서대로 고르시오.\n\n**<설명>**\n① 코드는 전송 데이터에 여러 개의 검사 비트를 추가하여 오류를 검출하고 수정까지 가능한 방법이다. 이 코드는 재전송 없이 수신 측에서 자체 수정하는 ② 방식에 속한다. 이에 반해 오류 발생 시 송신 측에 재전송을 요구하는 방식은 ③이라 하며, 여기에 포함되는 대표적 검출 기법으로 ④ 검사와 ⑤ 검사가 있다. ④ 검사는 데이터 블록 끝에 1비트 검사 비트를 추가하여 오류를 검출하고, ⑤ 검사는 송신측과 수신측이 동일한 특정 다항식을 사용하여 오류를 검출한다.\n\n**<보기>**\n㉠ CRC ㉡ FEC ㉢ BEC ㉣ NAK ㉤ Parity ㉥ MD5 ㉦ BCD ㉧ Hamming\n\n① ①㉧, ②㉡, ③㉢, ④㉤, ⑤㉠\n② ①㉠, ②㉢, ③㉡, ④㉤, ⑤㉧\n③ ①㉤, ②㉡, ③㉢, ④㉧, ⑤㉠\n④ ①㉧, ②㉢, ③㉡, ④㉠, ⑤㉤', 'MCQ', 1, '정답: 1. 해밍 코드는 오류 검출과 정정이 가능하고 FEC에 속한다. 재전송 기반 방식은 BEC이며 대표 검출 기법에는 패리티 검사와 CRC가 있다.\n\n**오답 풀이**\n- 1번: Hamming, FEC, BEC, Parity, CRC 순서가 맞다.\n- 2번: CRC와 Hamming의 위치가 바뀌었다.\n- 3번: Parity는 오류 정정 코드가 아니다.\n- 4번: FEC와 BEC의 의미가 바뀌었다.\n\n**보충 개념**\nFEC는 수신 측에서 오류를 스스로 정정하는 전방 오류 정정 방식이다. BEC는 오류 검출 후 재전송을 요청하는 후방 오류 제어 방식이다.',
   '오류 제어', 3, @mock_exam_id, 4, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'C언어' ORDER BY id LIMIT 1), '다음 C 코드의 출력 결과로 가장 적절한 것은?\n\n```c\n#include <stdio.h>\n\nstruct Test {\n    int i;\n    const char *g;\n};\n\nint main() {\n    struct Test test[] = {{1, "AB"}, {2, "DC"}, {3, "EB"}};\n    struct Test *p = &test[1];\n    printf("%s", p->g + (p->i - 1));\n    return 0;\n}\n```\n\n① C\n② D\n③ DC\n④ B', 'MCQ', 1, '정답: 1. p는 test[1]을 가리키므로 p->i는 2이고 p->g는 "DC"이다. p->g + 1은 문자열의 두 번째 문자 위치를 가리키므로 "C"가 출력된다.\n\n**오답 풀이**\n- 1번: 포인터가 문자열의 두 번째 문자 위치를 가리키므로 정답이다.\n- 2번: 문자열 시작 위치에서 출력한 경우이다.\n- 3번: p->g에 포인터 이동을 적용하지 않은 결과이다.\n- 4번: 다른 구조체 원소의 문자열과 혼동한 값이다.\n\n**보충 개념**\n문자열 포인터에 정수를 더하면 해당 문자 위치로 포인터가 이동한다. %s는 그 위치부터 널 문자 전까지 출력한다.',
   'C 포인터', 3, @mock_exam_id, 5, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'C언어' ORDER BY id LIMIT 1), '다음 C 코드의 출력 결과로 가장 적절한 것은?\n\n```c\n#include <stdio.h>\n\nint main(void) {\n    char str[] = "REPUBLICOFKOREA";\n    int a = 0;\n    while (str[a] != ''\\0'')\n        ++a;\n    putchar(str[a - 2]);\n    return 0;\n}\n```\n\n① A\n② E\n③ R\n④ O', 'MCQ', 2, '정답: 2. 문자열 "REPUBLICOFKOREA"의 길이는 15이고, a는 널 문자를 만날 때 15가 된다. str[a-2]는 str[13]으로 문자 E이다.\n\n**오답 풀이**\n- 1번: 마지막 문자 str[14]이다.\n- 2번: 뒤에서 두 번째 문자가 E이므로 정답이다.\n- 3번: 첫 문자와 혼동한 값이다.\n- 4번: 중간 문자 위치를 잘못 계산한 값이다.\n\n**보충 개념**\nC 문자열은 마지막에 널 문자 ''\\0''을 가진다. while 문이 종료될 때 인덱스는 문자열 길이와 같다.',
   'C 문자열', 2, @mock_exam_id, 6, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'C언어' ORDER BY id LIMIT 1), '다음 C 코드의 출력 결과로 가장 적절한 것은?\n\n```c\n#include <stdio.h>\n\nstruct Node {\n    struct Node* next;\n    unsigned int x;\n};\n\nint main() {\n    struct Node t1 = { 0, 5u };\n    struct Node t2 = { 0, 7u };\n    struct Node t3 = { 0, 11u };\n    t3.next = &t2;\n    t2.next = &t1;\n    struct Node* curr = &t3;\n    int sum = 0;\n    while (curr) {\n        sum = sum * 3 + curr->x;\n        curr = curr->next;\n    }\n    sum = (sum ^ 42u) + 100u;\n    printf("%u\\n", sum);\n}\n```\n\n① 187\n② 145\n③ 287\n④ 42', 'MCQ', 1, '정답: 1. 연결 순서는 t3(11) → t2(7) → t1(5)이다. sum은 0→11→40→125가 되고, 125 ^ 42는 87이므로 100을 더해 187이 출력된다.\n\n**오답 풀이**\n- 1번: 연결 리스트 순회와 XOR 계산이 맞다.\n- 2번: XOR 연산을 잘못 계산한 값이다.\n- 3번: 100을 더하는 위치 또는 값이 잘못된 결과이다.\n- 4번: XOR에 사용된 상수만 본 값이다.\n\n**보충 개념**\n^는 C에서 비트 XOR 연산자이다. 연결 리스트는 next 포인터가 가리키는 순서대로 순회한다.',
   'C 구조체', 4, @mock_exam_id, 7, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'Java' ORDER BY id LIMIT 1), '다음 Java 코드의 빈칸에 들어갈 올바른 키워드는?\n\n```java\ninterface Machine {\n    void run();\n}\n\nclass WashingMachine (____) Machine {\n    private String name;\n\n    public WashingMachine() {\n        this.name = "LG Washer";\n    }\n\n    public void run() {\n        System.out.println("Washing machine running");\n    }\n}\n```\n\n① extends\n② implements\n③ interface\n④ super', 'MCQ', 2, '정답: 2. Java에서 클래스가 인터페이스를 구현할 때는 implements 키워드를 사용한다.\n\n**오답 풀이**\n- 1번: extends는 클래스 상속 또는 인터페이스 간 상속에 사용된다.\n- 2번: 클래스가 인터페이스 Machine을 구현하므로 정답이다.\n- 3번: interface는 인터페이스를 선언할 때 사용한다.\n- 4번: super는 부모 클래스 생성자나 멤버를 참조할 때 사용한다.\n\n**보충 개념**\n클래스는 여러 인터페이스를 implements로 구현할 수 있다. 인터페이스의 추상 메서드는 구현 클래스에서 구현해야 한다.',
   'Java 인터페이스', 1, @mock_exam_id, 8, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'Python' ORDER BY id LIMIT 1), '다음 Python 코드의 출력 결과에서 ①~⑧에 들어갈 값으로 가장 적절한 것은?\n\n```python\ndata = [\n    [3, 5, 2, 4, 1],\n    [4, 5, 1],\n    [4, 4, 1, 5, 4],\n    [4, 5]\n]\nresult = {}\nfor index, lis in enumerate(data):\n    list_sum = sum(lis)\n    list_len = len(lis)\n    result[index] = (list_sum, list_len)\nprint(result)\n```\n\n**<출력 형식>**\n`{0: (①, ②), 1: (③, ④), 2: (⑤, ⑥), 3: (⑦, ⑧)}`\n\n① ①=15, ②=5, ③=10, ④=3, ⑤=18, ⑥=5, ⑦=9, ⑧=2\n② ①=14, ②=5, ③=10, ④=3, ⑤=18, ⑥=5, ⑦=9, ⑧=2\n③ ①=15, ②=4, ③=10, ④=3, ⑤=18, ⑥=5, ⑦=9, ⑧=2\n④ ①=15, ②=5, ③=9, ④=3, ⑤=18, ⑥=5, ⑦=9, ⑧=2', 'MCQ', 1, '정답: 1. 각 리스트의 합과 길이를 튜플로 저장한다. 합과 길이는 각각 (15,5), (10,3), (18,5), (9,2)이다.\n\n**오답 풀이**\n- 1번: 네 리스트의 합과 길이가 모두 맞다.\n- 2번: 첫 번째 리스트 합을 잘못 계산했다.\n- 3번: 첫 번째 리스트 길이를 잘못 계산했다.\n- 4번: 두 번째 리스트 합을 잘못 계산했다.\n\n**보충 개념**\nenumerate는 인덱스와 값을 함께 반환한다. sum은 리스트 원소의 합, len은 리스트 길이를 반환한다.',
   'Python 딕셔너리', 2, @mock_exam_id, 9, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'SQL' ORDER BY id LIMIT 1), '다음 테이블과 SQL을 확인하여 결과값으로 가장 적절한 것은?\n\n**<A 테이블>**\n| ID | 조건값 |\n|---:|---:|\n| 1 | 10 |\n| 2 | 20 |\n| 3 | 30 |\n| 4 | 40 |\n| 5 | 50 |\n\n```sql\nSELECT COUNT(*)\nFROM A\nWHERE 조건값 >= 20\n  AND 조건값 <= 50;\n```\n\n① 3\n② 4\n③ 5\n④ 0', 'MCQ', 2, '정답: 2. 조건값이 20 이상 50 이하인 행은 20, 30, 40, 50으로 총 4건이다.\n\n**오답 풀이**\n- 1번: 경계값 중 하나를 누락한 값이다.\n- 2번: 조건을 만족하는 행 수가 4건이므로 정답이다.\n- 3번: 10까지 포함한 전체 행 수이다.\n- 4번: 조건을 만족하는 행이 없다는 잘못된 판단이다.\n\n**보충 개념**\nSQL의 비교 조건에서 `>=`와 `<=`는 경계값을 포함한다. COUNT(*)는 조건을 만족하는 행의 수를 반환한다.',
   'SQL COUNT', 2, @mock_exam_id, 10, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '보안' ORDER BY id LIMIT 1), '다음 설명에 해당하는 인증 기술로 가장 적절한 것은?\n\n**<설명>**\n한 번 사용하면 즉시 폐기되어 재사용이 불가능하다. 서버와 토큰 또는 앱은 시간 동기화나 카운터 기반 방식으로 매번 새로운 값을 생성하고, 내부 검증은 해시 함수를 이용한 방식으로 서버에 평문을 저장하지 않고도 유효성을 확인할 수 있다. 은행 인증 등 고보안 영역에서 널리 사용되며 재전송 공격 방지와 사용자 편의성을 동시에 만족한다.\n\n① OTP\n② SSO\n③ OAuth\n④ Captcha', 'MCQ', 1, '정답: 1. OTP는 일회용 비밀번호로, 한 번 사용한 값은 재사용할 수 없다.\n\n**오답 풀이**\n- 1번: 시간 또는 카운터 기반 일회용 인증값을 사용하므로 정답이다.\n- 2번: SSO는 한 번의 로그인으로 여러 시스템에 접근하는 인증 방식이다.\n- 3번: OAuth는 권한 위임 프로토콜이다.\n- 4번: Captcha는 사람과 봇을 구분하기 위한 기술이다.\n\n**보충 개념**\nOTP는 TOTP처럼 시간 기반으로 만들거나 HOTP처럼 카운터 기반으로 만들 수 있다. 재전송 공격 방지에 효과적이다.',
   'OTP', 1, @mock_exam_id, 11, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'Java' ORDER BY id LIMIT 1), '다음 Java 코드의 빈칸에 들어갈 알맞은 단어는?\n\n```java\nclass Rectangle {\n    int width, height;\n\n    Rectangle(int width, int height) {\n        this.width = width;\n        this.height = height;\n    }\n}\n\nclass Square extends Rectangle {\n    Square(int a) {\n        ____(a, a);\n    }\n\n    int getSquareArea() {\n        return width * height;\n    }\n}\n```\n\n① this\n② super\n③ extends\n④ implements', 'MCQ', 2, '정답: 2. 자식 클래스 생성자에서 부모 클래스 생성자를 호출할 때는 super(...)를 사용한다.\n\n**오답 풀이**\n- 1번: this(...)는 같은 클래스의 다른 생성자를 호출할 때 사용한다.\n- 2번: 부모 생성자 Rectangle(int, int)를 호출해야 하므로 정답이다.\n- 3번: extends는 클래스 상속 선언에 사용된다.\n- 4번: implements는 인터페이스 구현에 사용된다.\n\n**보충 개념**\nJava에서 부모 클래스에 기본 생성자가 없으면 자식 생성자에서 명시적으로 super(...)를 호출해야 한다. super 호출은 생성자 첫 문장이어야 한다.',
   'Java super', 2, @mock_exam_id, 12, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '보안' ORDER BY id LIMIT 1), '다음 설명에 해당하는 인증 및 자원 접근 방식으로 가장 적절한 것은?\n\n**<설명>**\n사용자가 새로운 사이트에 가입하지 않고 평소 이용하던 서비스의 계정으로 로그인할 수 있게 해준다. 사용자의 비밀번호는 전달되지 않으며, 사용자가 승인한 범위에 대해서만 접근 권한이 위임된다. 직접 인증보다 인가 절차를 통해 접근 권한을 제3자에게 부여하는 데 초점이 있으며, Access Token을 이용해 API를 호출한다.\n\n① OAuth\n② FTP\n③ Kerberos\n④ LDAP', 'MCQ', 1, '정답: 1. OAuth는 사용자의 비밀번호를 공유하지 않고 제3자 애플리케이션에 제한된 접근 권한을 위임하는 인가 프레임워크이다.\n\n**오답 풀이**\n- 1번: Access Token 기반 권한 위임 방식이므로 정답이다.\n- 2번: FTP는 파일 전송 프로토콜이다.\n- 3번: Kerberos는 티켓 기반 네트워크 인증 프로토콜이다.\n- 4번: LDAP는 디렉터리 서비스 접근 프로토콜이다.\n\n**보충 개념**\nOAuth는 소셜 로그인과 API 권한 위임에 자주 사용된다. 인증 자체보다는 인가와 권한 위임에 중점을 둔다.',
   'OAuth', 1, @mock_exam_id, 13, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '데이터베이스 이론' ORDER BY id LIMIT 1), '다음 릴레이션 R과 S에 대해 관계대수식 `R ÷ S`의 결과로 가장 적절한 것은?\n\n**<R>**\n| A | B |\n|---|---|\n| a1 | b1 |\n| a1 | b2 |\n| a2 | b1 |\n\n**<S>**\n| B |\n|---|\n| b1 |\n| b2 |\n\n**<결과 형식>**\nR ÷ S는 S의 모든 B 값과 짝을 이루는 A 값을 반환한다.\n\n① A\na1\n② A\na2\n③ A\na1\na2\n④ 결과 없음', 'MCQ', 1, '정답: 1. a1은 b1, b2와 모두 짝을 이루지만 a2는 b1과만 짝을 이루므로 결과는 a1이다.\n\n**오답 풀이**\n- 1번: S의 모든 B 값을 만족하는 A가 a1이므로 정답이다.\n- 2번: a2는 b2와의 조합이 없어 조건을 만족하지 않는다.\n- 3번: a2를 잘못 포함했다.\n- 4번: a1이 조건을 만족하므로 공집합이 아니다.\n\n**보충 개념**\n관계 나눗셈은 ''모든 조건을 만족하는 값''을 찾는 연산이다. 예를 들어 모든 과목을 수강한 학생을 찾는 문제에 활용된다.',
   '관계대수 나눗셈', 3, @mock_exam_id, 14, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'C언어' ORDER BY id LIMIT 1), '다음 C 코드의 출력 결과로 가장 적절한 것은?\n\n```c\n#include <stdio.h>\n\nint main() {\n    int x = 7, y = 4, z;\n    z = y % 3 < 3 ? 2 : 1;\n    z = z & z >> 1;\n    z = x > 5 && z <= 3 ? z * x : z / x;\n    printf("%d", z);\n    return 0;\n}\n```\n\n① 0\n② 1\n③ 7\n④ 14', 'MCQ', 1, '정답: 1. y%3은 1이고 1<3이 참이므로 z=2이다. `z & z >> 1`은 2 & 1이므로 0이다. 마지막 조건은 참이지만 z*x가 0이므로 0이 출력된다.\n\n**오답 풀이**\n- 1번: 비트 연산과 삼항 연산 결과가 맞다.\n- 2번: 2 & 1을 1로 잘못 계산한 값이다.\n- 3번: z를 1로 보고 x를 곱한 값이다.\n- 4번: 첫 번째 z=2에 x를 곱한 값이다.\n\n**보충 개념**\n시프트 연산 `>>`가 `&`보다 우선순위가 높다. 따라서 `z & z >> 1`은 `z & (z >> 1)`로 계산된다.',
   'C 비트 연산', 3, @mock_exam_id, 15, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '데이터베이스 이론' ORDER BY id LIMIT 1), '관계형 데이터베이스 개념 설명과 용어의 연결로 가장 적절한 것은?\n\n**<설명>**\nㄱ. 테이블에서 한 행(Row)을 의미하며, 하나의 레코드를 구성하는 요소\nㄴ. 실제 데이터가 저장되어 있는 테이블의 내용 전체를 의미하며, 데이터의 상태를 나타낸다.\nㄷ. 테이블에 저장된 행(Row)의 총 개수를 의미한다.\n\n**<보기>**\n스키마, 속성, 튜플, 차수, 인스턴스, 카디널리티\n\n① ㄱ-튜플, ㄴ-인스턴스, ㄷ-카디널리티\n② ㄱ-속성, ㄴ-스키마, ㄷ-차수\n③ ㄱ-카디널리티, ㄴ-인스턴스, ㄷ-튜플\n④ ㄱ-튜플, ㄴ-스키마, ㄷ-차수', 'MCQ', 1, '정답: 1. 한 행은 튜플, 릴레이션의 실제 데이터 상태는 인스턴스, 행의 총 개수는 카디널리티이다.\n\n**오답 풀이**\n- 1번: 세 용어가 모두 올바르게 연결되었다.\n- 2번: 속성은 열이고 스키마는 구조이다.\n- 3번: 튜플과 카디널리티가 바뀌었다.\n- 4번: 스키마와 차수의 의미가 맞지 않는다.\n\n**보충 개념**\n차수는 속성 수, 카디널리티는 튜플 수이다. 스키마는 데이터베이스의 구조, 인스턴스는 특정 시점의 실제 데이터이다.',
   '관계형 데이터 모델', 1, @mock_exam_id, 16, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'Java' ORDER BY id LIMIT 1), '다음 Java 코드의 출력 결과로 가장 적절한 것은?\n\n```java\nenum Tri {\n    A("A"), B("AB"), C("ABC");\n\n    private String code;\n\n    Tri(String code) {\n        this.code = code;\n    }\n\n    public String code() {\n        return code;\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Tri t = Tri.values()[Tri.A.name().length()];\n        System.out.print(t.code());\n    }\n}\n```\n\n① A\n② AB\n③ ABC\n④ 오류', 'MCQ', 2, '정답: 2. Tri.A.name()은 "A"이고 길이는 1이다. Tri.values()[1]은 B이므로 B의 code 값인 "AB"가 출력된다.\n\n**오답 풀이**\n- 1번: values()[0]일 때의 값이다.\n- 2번: 인덱스 1에 해당하는 B의 code이므로 정답이다.\n- 3번: values()[2]일 때의 값이다.\n- 4번: enum 접근과 배열 인덱스 모두 유효하다.\n\n**보충 개념**\nEnum.values()는 선언 순서대로 enum 상수 배열을 반환한다. name()은 enum 상수명을 문자열로 반환한다.',
   'Java enum', 2, @mock_exam_id, 17, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '보안' ORDER BY id LIMIT 1), '다음 접근통제 모델 설명과 용어의 연결로 가장 적절한 것은?\n\n**<설명>**\nㄱ. 중앙에서 보안 정책을 일괄적으로 설정하며, 주체가 임의로 수정할 수 없다. 보안 등급에 따라 접근 여부가 결정된다.\nㄴ. 조직 내 직무나 역할에 따라 접근 권한을 부여한다. 역할에 권한을 묶어 관리하므로 직무 변경 시 역할만 변경하면 된다.\nㄷ. 자원의 소유자가 접근 권한을 자유롭게 부여하거나 회수할 수 있다.\n\n**<보기>**\nDAC, MAC, RBAC\n\n① ㄱ-MAC, ㄴ-RBAC, ㄷ-DAC\n② ㄱ-DAC, ㄴ-RBAC, ㄷ-MAC\n③ ㄱ-RBAC, ㄴ-MAC, ㄷ-DAC\n④ ㄱ-MAC, ㄴ-DAC, ㄷ-RBAC', 'MCQ', 1, '정답: 1. 강제 접근통제는 MAC, 역할 기반 접근통제는 RBAC, 임의 접근통제는 DAC이다.\n\n**오답 풀이**\n- 1번: 세 접근통제 방식이 모두 올바르게 연결되었다.\n- 2번: DAC와 MAC이 바뀌었다.\n- 3번: MAC과 RBAC가 바뀌었다.\n- 4번: DAC와 RBAC가 바뀌었다.\n\n**보충 개념**\nMAC은 중앙 정책과 보안 등급 기반, DAC는 소유자 권한 위임 기반, RBAC는 역할 기반 권한 관리 방식이다.',
   '접근통제', 2, @mock_exam_id, 18, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = '소프트웨어 설계' ORDER BY id LIMIT 1), '다음 테스트케이스 구성요소 설명의 빈칸에 들어갈 보기를 왼쪽부터 순서대로 고르시오.\n\n**<설명>**\n테스트케이스 표에는 입력 전제나 검증 대상 조건, 테스트에 사용할 입력값, 실행 후 기대되는 결과를 기재하는 칸이 제시되어 있다.\n\n**<보기>**\nㄱ. 테스트 조건\nㄴ. 테스트 환경\nㄷ. 테스트 유형\nㄹ. 테스트 데이터\nㅁ. 예상 결과\nㅂ. 수행 단계\nㅅ. 성공/실패 기준\n\n① ㄱ, ㄹ, ㅁ\n② ㄴ, ㄹ, ㅁ\n③ ㄱ, ㅂ, ㅅ\n④ ㄷ, ㄹ, ㅁ', 'MCQ', 1, '정답: 1. 왼쪽부터 테스트 조건, 테스트 데이터, 예상 결과에 해당한다.\n\n**오답 풀이**\n- 1번: 조건, 데이터, 예상 결과의 흐름이 맞다.\n- 2번: 테스트 환경은 실행 환경 정보로, 검증 조건 칸과 다르다.\n- 3번: 수행 단계와 성공/실패 기준은 제시된 세 칸의 의미와 다르다.\n- 4번: 테스트 유형은 테스트 분류에 해당한다.\n\n**보충 개념**\n테스트케이스에는 테스트 조건, 입력 데이터, 수행 절차, 예상 결과, 판정 기준 등이 포함될 수 있다.',
   '테스트케이스', 2, @mock_exam_id, 19, 'NONE', NULL, NOW(6), NOW(6)),
  ((SELECT id FROM subject WHERE name = 'SQL' ORDER BY id LIMIT 1), '다음 A 테이블을 참고하여 SQL 실행 결과로 가장 적절한 것은?\n\n**<A>**\n| col1 | col2 |\n|---:|---:|\n| 1 | 3 |\n| 2 | 1 |\n| 3 | 2 |\n| 4 | 5 |\n| 2 | NULL |\n\n```sql\nSELECT COUNT(col2)\nFROM A\nWHERE col1 IN (2, 3)\n   OR col2 IN (3, 5);\n```\n\n① 2\n② 3\n③ 4\n④ 5', 'MCQ', 3, '정답: 3. 조건을 만족하는 행은 5행이지만, 그중 마지막 행은 col2가 NULL이다. COUNT(col2)는 NULL을 제외하므로 결과는 4이다.\n\n**오답 풀이**\n- 1번: 조건 만족 행을 일부만 센 값이다.\n- 2번: col1 IN 조건 일부만 계산한 값이다.\n- 3번: 조건 만족 행 중 col2가 NULL이 아닌 값의 개수이므로 정답이다.\n- 4번: COUNT(*)처럼 조건 만족 전체 행 수를 센 값이다.\n\n**보충 개념**\nCOUNT(col2)는 NULL을 제외하고 센다. OR 조건은 둘 중 하나라도 만족하면 TRUE이다.',
   'SQL COUNT', 3, @mock_exam_id, 20, 'NONE', NULL, NOW(6), NOW(6))
;